export const tastings = [
  {
    id: "1",
    coffeeshop: "Good News",
    location: "27 bis rue Mademoiselle, Paris 15e",
    drinkName: "Matcha",
    category: "Matcha",
    categoryEmoji: "🍵",
    description: "Un matcha bien dosé, ni trop amer ni trop sucré. Le café est lumineux et calme, parfait pour une vraie pause. On sent qu'ils prennent soin de la qualité du thé.",
    ratingZay: 7.2,
    ratingKouceyla: 5,
    photos: ["/images/tastings/matcha_good_news.jpeg"],
  },
  {
    id: "2",
    coffeeshop: "Alva",
    location: "Bd d'Ormesson, Enghien-les-Bains",
    drinkName: "Matcha",
    category: "Matcha",
    categoryEmoji: "🍵",
    description: "Texture crémeuse mais le matcha manquait de caractère, un peu trop discret. Le cadre d'Enghien est vraiment cosy et l'accueil chaleureux.",
    ratingZay: 3,
    ratingKouceyla: 6,
    photos: ["/images/tastings/cafe_alva.jpeg"],
  },
  {
    id: "3",
    coffeeshop: "Okido",
    location: "8 rue du Dr Demirleau, Montmorency",
    drinkName: "Matcha Passion",
    category: "Matcha",
    categoryEmoji: "🍵",
    description: "Un coup de cœur. L'acidité du fruit de la passion contre la végétalité du matcha, c'est une combinaison qui fonctionne à merveille. Le visuel en couches est magnifique.",
    ratingZay: 10,
    ratingKouceyla: 8,
    photos: ["/images/tastings/matcha_okido_boisson.jpeg"],
  },
  {
    id: "4",
    coffeeshop: "Café Kitsuné",
    location: "51 Galerie de Montpensier, Paris 1er",
    drinkName: "Café",
    category: "Café",
    categoryEmoji: "☕",
    description: "Iconic. La terrasse du Palais Royal, le café soigné, le service impeccable — tout est à la hauteur de la réputation. Un endroit où on prend le temps.",
    ratingZay: 10,
    ratingKouceyla: 9,
    photos: ["/images/tastings/matcha_cafe_kitsune.jpeg", "/images/tastings/latte_caramel_kitsune_cafe.jpeg"],
  },
  {
    id: "5",
    coffeeshop: "The Coffee.",
    location: "40 rue des Gravilliers, Paris 3e",
    drinkName: "Matcha",
    category: "Matcha",
    categoryEmoji: "🍵",
    description: "Décevant pour l'enseigne. Trop sucré, le matcha se perd complètement derrière. Le cadre est joli mais la boisson ne suit pas.",
    ratingZay: 5,
    ratingKouceyla: 1,
    photos: ["/images/tastings/thecoffee.JPG"],
  },
  {
    id: "6",
    coffeeshop: "Isaka",
    location: "9 rue Thérèse, Paris 1er",
    drinkName: "Ube Latte",
    category: "Ube",
    categoryEmoji: "💜",
    description: "Visuellement bluffant, goût surprenant. L'ube apporte une douceur florale vraiment unique qu'on ne retrouve nulle part ailleurs. Un endroit à part.",
    ratingZay: 8.3,
    ratingKouceyla: 8,
    photos: ["/images/tastings/ubeisaka.JPG", "/images/tastings/ube_latte_isaka.jpeg"],
  },
  {
    id: "7",
    coffeeshop: "Alva",
    location: "Bd d'Ormesson, Enghien-les-Bains",
    drinkName: "Ube Latte",
    category: "Ube",
    categoryEmoji: "💜",
    description: "Moins percutant que l'Isaka mais agréable. La couleur violette est toujours aussi belle, la texture bien crémeuse.",
    ratingZay: 7.2,
    ratingKouceyla: 6,
    photos: [],
  },
  {
    id: "8",
    coffeeshop: "Okido",
    location: "8 rue du Dr Demirleau, Montmorency",
    drinkName: "Hojicha",
    category: "Hojicha",
    categoryEmoji: "🍂",
    description: "On n'a vraiment pas accroché. Le hojicha avait un goût très fumé, presque amer, qui ne nous a pas convaincues. Pas notre style.",
    ratingZay: 1,
    ratingKouceyla: 1,
    photos: [],
  },
  {
    id: "9",
    coffeeshop: "Okido",
    location: "8 rue du Dr Demirleau, Montmorency",
    drinkName: "Tiramisu Latte",
    category: "Café",
    categoryEmoji: "☕",
    description: "L'idée est originale et on applaudit la créativité, mais l'exécution était trop sucrée. Le café se perdait complètement. On est restées mitigées.",
    ratingZay: 2,
    ratingKouceyla: 4,
    photos: [],
  },
  {
    id: "10",
    coffeeshop: "Alva",
    location: "Bd d'Ormesson, Enghien-les-Bains",
    drinkName: "Café Caramel",
    category: "Café",
    categoryEmoji: "☕",
    description: "Trop caramélisé à notre goût — le sucre écrase complètement le café. Si t'aimes les boissons très douces, ça peut plaire, mais ce n'est pas notre préférence.",
    ratingZay: 3,
    ratingKouceyla: 2,
    photos: ["/images/tastings/icecoffecaramelalva.jpg", "/images/tastings/cafe_alva.jpeg"],
  },
  {
    id: "11",
    coffeeshop: "Saddle",
    location: "10 rue Hélène Vagliano, Cannes",
    drinkName: "Matcha",
    category: "Matcha",
    categoryEmoji: "🍵",
    description: "Le meilleur matcha goûté à ce jour — et à Cannes en plus ! Texture soyeuse, amertume parfaite, rien à redire. Une découverte qu'on n'attendait pas.",
    ratingZay: 10,
    ratingKouceyla: 10,
    photos: [],
  },
  {
    id: "12",
    coffeeshop: "Saddle",
    location: "10 rue Hélène Vagliano, Cannes",
    drinkName: "Café Caramel",
    category: "Café",
    categoryEmoji: "☕",
    description: "Un équilibre café-caramel incroyable, là où les autres échouent. Le caramel est présent sans être envahissant. On comprend pourquoi c'est un 10/10.",
    ratingZay: 8,
    ratingKouceyla: 10,
    photos: [],
  },
  {
    id: "13",
    coffeeshop: "Okido",
    location: "8 rue du Dr Demirleau, Montmorency",
    drinkName: "Café Caramel",
    category: "Café",
    categoryEmoji: "☕",
    description: "Correct mais sans surprise. Honnête, bien fait, mais après le Saddle on ne peut pas s'empêcher de comparer. Il lui manque ce petit quelque chose.",
    ratingZay: 6,
    ratingKouceyla: 6,
    photos: ["/images/tastings/matcha_okido_boisson.jpeg"],
  },
  {
    id: "14",
    coffeeshop: "Creamy Daily",
    location: "49 rue Sainte-Anne, Paris 2e",
    drinkName: "Creamy Fraise",
    category: "Fruité",
    categoryEmoji: "🍓",
    description: "Frais, fruité, crémeux — tout ce qu'on attendait. La fraise est vraiment présente, pas artificielle du tout. Un incontournable quand on passe dans le 2e.",
    ratingZay: 10,
    ratingKouceyla: 8,
    photos: ["/images/tastings/creamy_daily_fraise.jpeg"],
  },
  {
    id: "15",
    coffeeshop: "Creamy Daily",
    location: "49 rue Sainte-Anne, Paris 2e",
    drinkName: "Creamy Mangue",
    category: "Fruité",
    categoryEmoji: "🥭",
    description: "Légèrement moins intense que la fraise mais toujours très bon. La mangue apporte une douceur tropicale qui change des boissons habituelles.",
    ratingZay: 10,
    ratingKouceyla: 7,
    photos: [],
  },
];
