export const tastings = [
  {
    id: "1",
    coffeeshop: "Good News",
    location: "27 bis rue Mademoiselle, Paris 15e",
    drinkName: "Matcha",
    category: "Matcha",
    categoryEmoji: "🍵",
    ratingZay: 7.2,
    ratingKouceyla: 5,
    photos: [],
  },
  {
    id: "2",
    coffeeshop: "Alva",
    location: "Bd d'Ormesson, Enghien-les-Bains",
    drinkName: "Matcha",
    category: "Matcha",
    categoryEmoji: "🍵",
    ratingZay: 3,
    ratingKouceyla: 6,
    photos: [],
  },
  {
    id: "3",
    coffeeshop: "Okido",
    location: "8 rue du Dr Demirleau, Montmorency",
    drinkName: "Matcha Passion",
    category: "Matcha",
    categoryEmoji: "🍵",
    ratingZay: 10,
    ratingKouceyla: 8,
    photos: [],
  },
  {
    id: "4",
    coffeeshop: "Café Kitsuné",
    location: "51 Galerie de Montpensier, Paris 1er",
    drinkName: "Café",
    category: "Café",
    categoryEmoji: "☕",
    ratingZay: 10,
    ratingKouceyla: 9,
    photos: [],
  },
  {
    id: "5",
    coffeeshop: "The Coffee.",
    location: "40 rue des Gravilliers, Paris 3e",
    drinkName: "Café",
    category: "Café",
    categoryEmoji: "☕",
    ratingZay: 5,
    ratingKouceyla: 1,
    photos: ["/images/tastings/thecoffee.JPG"],
  },
  {
    id: "6",
    coffeeshop: "Isaka",
    location: "9 rue Thérèse, Paris 1er",
    drinkName: "Ube Latte",
    category: "Ube",
    categoryEmoji: "💜",
    ratingZay: 8.3,
    ratingKouceyla: 8,
    photos: ["/images/tastings/ubeisaka.JPG"],
  },
  {
    id: "7",
    coffeeshop: "Alva",
    location: "Bd d'Ormesson, Enghien-les-Bains",
    drinkName: "Ube Latte",
    category: "Ube",
    categoryEmoji: "💜",
    ratingZay: 7.2,
    ratingKouceyla: 6,
    photos: [],
  },
  {
    id: "8",
    coffeeshop: "Okido",
    location: "8 rue du Dr Demirleau, Montmorency",
    drinkName: "Hojicha",
    category: "Hojicha",
    categoryEmoji: "🍂",
    ratingZay: 1,
    ratingKouceyla: 1,
    photos: [],
  },
  {
    id: "9",
    coffeeshop: "Okido",
    location: "8 rue du Dr Demirleau, Montmorency",
    drinkName: "Tiramisu Latte",
    category: "Café",
    categoryEmoji: "☕",
    ratingZay: 2,
    ratingKouceyla: 4,
    photos: [],
  },
  {
    id: "10",
    coffeeshop: "Alva",
    location: "Bd d'Ormesson, Enghien-les-Bains",
    drinkName: "Café Caramel",
    category: "Café",
    categoryEmoji: "☕",
    ratingZay: 3,
    ratingKouceyla: 2,
    photos: ["/images/tastings/icecoffecaramelalva.jpg"],
  },
  {
    id: "11",
    coffeeshop: "Saddle",
    location: "10 rue Hélène Vagliano, Cannes",
    drinkName: "Matcha",
    category: "Matcha",
    categoryEmoji: "🍵",
    ratingZay: 10,
    ratingKouceyla: 10,
    photos: [],
  },
  {
    id: "12",
    coffeeshop: "Saddle",
    location: "10 rue Hélène Vagliano, Cannes",
    drinkName: "Café Caramel",
    category: "Café",
    categoryEmoji: "☕",
    ratingZay: 8,
    ratingKouceyla: 10,
    photos: [],
  },
  {
    id: "13",
    coffeeshop: "Okido",
    location: "8 rue du Dr Demirleau, Montmorency",
    drinkName: "Café Caramel",
    category: "Café",
    categoryEmoji: "☕",
    ratingZay: 6,
    ratingKouceyla: 6,
    photos: [],
  },
  {
    id: "14",
    coffeeshop: "Creamy Daily",
    location: "49 rue Sainte-Anne, Paris 2e",
    drinkName: "Creamy Fraise",
    category: "Fruité",
    categoryEmoji: "🍓",
    ratingZay: 10,
    ratingKouceyla: 8,
    photos: [],
  },
  {
    id: "15",
    coffeeshop: "Creamy Daily",
    location: "49 rue Sainte-Anne, Paris 2e",
    drinkName: "Creamy Mangue",
    category: "Fruité",
    categoryEmoji: "🥭",
    ratingZay: 10,
    ratingKouceyla: 7,
    photos: [],
  },
];
